### ISSUE TITLE
Dropdown appears empty

### ISSUE THREAD

**Issue by wfjamesk** [Dedac/RestDataMappingPicklist#32]
![Screenshot 2021-07-08 111427](https://user-images.githubusercontent.com/87141627/124957025-3d5a6480-dfde-11eb-97cc-15350dc84fb3.png)
![Screenshot 2021-07-08 111548](https://user-images.githubusercontent.com/87141627/124957029-3d5a6480-dfde-11eb-8ae4-ec8d346ec448.png)

Dropdown appears empty until you start to type in the field.

**Comment by Dedac** [comment]
@wfjamesk I released version .2.7 Today see if that fixes this issue

**Comment by wfjamesk** [comment]
Yes.  Everything seems to be working correctly now.  Thank you for resolving this issue.
