### ISSUE TITLE
Where to enable CORS for adding https://dedac.gallerycdn.vsassets.io domain

### ISSUE THREAD

**Issue by josmunpav** [Dedac/RestDataMappingPicklist#33]
Hi,

I installed this extension from the Marketplace. It installs fine but it does not work as expected as I can't get any results in my picklist. I tested my Rest service and works as expected. I checked the extension and at the overview in the Marketplace it says 

_Add https://dedac.gallerycdn.vsassets.io to the CORS allowed domains to use the extension_

I have been trying to find where to enable CORS for this domain on Azure Devops but cannot find it anywhere. Any help please? I'm fairly new to Azure Devops.

Thanks in advance.

**Comment by Dedac** [comment]
You don't have to set the up for a rest call in Azure Devops

**Comment by Dedac** [comment]
It is the server that you are calling to that needs to allow the address.

**Comment by josmunpav** [comment]
Excellent thanks for the tip
