### ISSUE TITLE
if the parameter is in URL, how to set?

### ISSUE THREAD

**Issue by HeyanHe** [Dedac/RestDataMappingPicklist#37]
https://dev.azure.com/{Organization Name}/_apis/projects?api-version=6.1-preview.4

These my settings.
![image](https://user-images.githubusercontent.com/89380571/130411838-0298c00f-bfe4-4fc7-b21e-2770d3048cdb.png)
![image](https://user-images.githubusercontent.com/89380571/130411956-cb766bbb-8f14-4602-89c9-5b435b4f6f4f.png)

**Comment by Dedac** [comment]
Just use the correct org name in the url. The url parameters are after the address, so you don't need to use them in this case

**Comment by HeyanHe** [comment]
OK. I had update configuration item, and ran success. Very Tanks!
