### ISSUE TITLE
Provide bearer token authentication

### ISSUE THREAD

**Issue by sahlex** [Dedac/RestDataMappingPicklist#4]
Hi there.

Many thanks vor providing the RestDataMappingPicklist. 
Would it be possible to build a more sophisticated authorization support like Bearer Token? Using a specific username is not always possible due to security restrictions.

Best,
Alexander

**Comment by Dedac** [comment]
This would be a good improvement - I think that we might be able to do it with just a checkbox for Token Auth, and a little bit more logic in [rest-call.ts](https://github.com/Dedac/RestDataMappingPicklist/blob/main/src/rest-call.ts)

I may get a chance to look into it, but PRs are welcome

**Comment by sahlex** [comment]
Maybe the simplest way to do this would be to provide additional headers to the request the same way as for the request parameters.
