### ISSUE TITLE
Question - Call Operation 

### ISSUE THREAD

**Issue by emosegue** [Dedac/RestDataMappingPicklist#67]
Hi all!
First of all I thank you for the extension, excellent work!

I already made it work, now I need to optimize the times because the component takes a long time to load.

Context: The REST service fetches approximately 45k items in the JSON. I did this without parameterization because I assumed that the component does not support successive AJAX calls, but that it calls only once each time the work item is opened. this is so?

Otherwise, you would need to call with the parameter of what the user is currently typing. Can that be done?

Greetings

**Comment by Dedac** [comment]
It will only make the call the one time when the form loads, attaching the load to other form edit events would probably be possible, but would require configuration on which field changes to watch to make new calls.  It would be too heavy to have the calls happen for every field change.  
Loading 45k items into the drop down is probably also taking a while, so ideally you could limit that list based on what someone needs to select.  Is there some way that you could use more than one field for the data?  

Depending on your control of the api, or if you can use a query with it you may be able to reduce the size of the individual records - that might reduce the load times some.

**Comment by emosegue** [comment]
Thank you very much for the response Dedac.
I answer below

1. We are using the platform to log problems, and the drop down consumes data from sites that do not depend on any field in the form. And if so, the user could arbitrarily modify it without any inconvenience. For this reason, it is not feasible to associate the call to another field.

2. The option to associate the call to another field is similar to the previous one, maybe it could be the solution, but it makes me think that it could add complexity to the load.

3. The API was developed by my team specifically for this use case, therefore it is optimized to only return the name used in the drop down. The structure of the JSON is as follows:

{
"data":[
{"name": "example1" },
{"name": "example2" }]
}

4. The API call is made by the service published in the domain https://dedac.gallerycdn.vsassets.io? Or how does this intervene in the process, I ask why perhaps by installing the extension that is currently published on a server, call times are reduced.

Greetings

**Comment by emosegue** [comment]
Hello again Dedac , looking at the Network tab of the browser, I realized that the server returns a file named selector.js that weighs 1.9MB. API call takes 489ms

![image](https://user-images.githubusercontent.com/11935515/151049236-1f04e5ec-c7b0-4ecd-a485-571367118fe2.png)

When I open the file, I see that it has 1,867,856 characters, where 1.452.401 are the base 64 encoded JSON with the same code of selector.js

![image](https://user-images.githubusercontent.com/11935515/151049510-1c5974f4-4eb8-42e9-ad49-d6eba27a2cf3.png)

Maybe I don't understand what role it fulfills, but is it possible to remove it to reduce the size and, consequently, the time the server sends it?

Best regards

**Comment by Dedac** [comment]
1.9MB there is the core of the webpacked extension, not a lot that I know about that I can do for it - the base bits of React and such that need to be included with the way that Azure DevOps Extensions work.  If I am missing something in the webpack commands that would improve the build, I would love to know :)

**Comment by emosegue** [comment]
Hello Dedac, I don't really know that stage, my question was simply about the selector.js file that comes from the server.

Could you guide me a little on how to test it in my environment to try to modify it according to the needs of my domain? I ran the commands that appear in the home but I have no idea how to test their operation.

Thanks

**Comment by Dedac** [comment]
Sorry it took a bit to get back to you 
- You can start [here](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops) for the overall view.
- Create a developer [account on the marketplace](https://marketplace.visualstudio.com/manage) and then you can publish a private version of the extension with the output files from the build.  
- Add your own test organization, then you can add your build of the extension to your test org.  Configure the extension as normal and see how it does 😃
