### ISSUE TITLE
[Bug]: cors value in documentation needs fixing

### ISSUE THREAD

**Issue by oriacct** [Dedac/RestDataMappingPicklist#97]
### What happened?

When calling an external api, this CORS value needs to be added:
https://martinlundhgren.gallerycdn.vsassets.io/

In your documentation here (https://marketplace.visualstudio.com/items?itemName=MartinLundhgren.RestDataMappingPicklist&ssr=false#overview) it suggests another cdn value is required (https://dedac.gallerycdn.vsassets.io/).

Adding the alternative one fixes the problem.

### Version

1.0.2 (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dedac** [comment]
If you are seeing "https://martinlundhgren.gallerycdn.vsassets.io/" you installed someone else's fork of my extension (Who didn't change any of the documentation, and may not be up to date with the latest version). 

If you install the original https://marketplace.visualstudio.com/items?itemName=dedac.RestDataMappingPicklist the CORS value will be correct
