### ISSUE TITLE
[Bug]: System.Id not able to be used for URL parameter

### ISSUE THREAD

**Issue by oriacct** [Dedac/RestDataMappingPicklist#98]
### What happened?

When calling an API, and a URL Parameter is required, it seems System level variables are not passed.

Rest Call URL Parameters used:
![image](https://user-images.githubusercontent.com/4378130/185641838-feb9bcce-f3fc-455a-9f21-34946447682c.png)

Browser api call - field blank:
![image](https://user-images.githubusercontent.com/4378130/185642080-e1ad1d15-4400-428f-bd9a-5692be15a4b6.png)

### Version

1.0.2 (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dedac** [comment]
System fields worked fine if they were strings, but it was limiting values in the request to string values.
I added some code to ensure numbers, dates, iterations, etc could all be set as part of the rest call.  System.Id should work now in version 0.4 - ensure you have [my extension installed](https://marketplace.visualstudio.com/items?itemName=dedac.RestDataMappingPicklist), and not a fork.

**Comment by oriacct** [comment]
Worked! ty.
